title: Praktikum – Lichtfolge
description: Dokumentation für das Praktikumsmodul Lichtfolge
author: Tobias Lauxtermann - WAGO GmbH & Co. KG
url: "https://wago-enterprise-education.github.io/praktikum-lichtfolge/"
lang: de
markdown: kramdown
remote_theme: wago-enterprise-education/wago-github-pages-theme
plugins:
- jemoji
- jekyll-redirect-from
- jekyll-relative-links